---
deployment:
  # some explanations below
  # 1. Shared hostings disallow symbolic links and private pip installation
  # so, we need to do it manually (this ge-pip thing)
  # 2. We should be mandatory python 3.6
  # 3. We have problem with psycopg2-binary and psycopg2 at all - it is native drive
  # that have system dependent parts. This will not work on shared hosting - use psycopg (pure python implementation)
  tasks:
    - export DEPLOYPATH=/home/rcsjkudmfy/myflaskapp/
    - /bin/cp -R * $DEPLOYPATH
    - cd $DEPLOYPATH
    - rm -rf venv
    - python3 -m venv --without-pip --copies venv
    - source venv/bin/activate
    - curl https://bootstrap.pypa.io/pip/3.6/get-pip.py -o get-pip.py
    - python get-pip.py
    - rm get-pip.py
    - pip install -r requirements.txt
    - mkdir -p tmp
    - touch tmp/restart.txt
