"""Add login rate limiting fields to User

Revision ID: 03a1b3c908b2
Revises: d4f3b2c9f0a1
Create Date: 2026-01-31 14:13:48.276545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03a1b3c908b2'
down_revision = 'd4f3b2c9f0a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('login_attempts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_attempt_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_attempt_time')
        batch_op.drop_column('login_attempts')

    # ### end Alembic commands ###
