"""Add parent_folder_id to CourseContentFolder for subfolder support

Revision ID: 10102302b31e
Revises: 
Create Date: 2025-12-30 16:45:45.215295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10102302b31e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_content_folder', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_folder_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'course_content_folder', ['parent_folder_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_content_folder', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('parent_folder_id')

    # ### end Alembic commands ###
