"""Remove course tab label fields

Revision ID: 2b9425c43d10
Revises: b510be4dc5b3
Create Date: 2026-01-19 17:16:44.463156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b9425c43d10'
down_revision = 'b510be4dc5b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('tab_reviews_label')
        batch_op.drop_column('tab_assignments_label')
        batch_op.drop_column('tab_announcements_label')
        batch_op.drop_column('tab_content_label')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tab_content_label', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tab_announcements_label', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tab_assignments_label', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tab_reviews_label', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
