"""Add preview_drive_view_link field to Resource model

Revision ID: 312c4937cc2e
Revises: 95c61dd4b257
Create Date: 2026-01-16 15:08:46.587914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '312c4937cc2e'
down_revision = '95c61dd4b257'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preview_drive_view_link', sa.String(length=300), nullable=True))
        # is_image_file column already exists from manual addition

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.drop_column('preview_drive_view_link')
        # is_image_file column was added manually, not by this migration

    # ### end Alembic commands ###
