"""Add preview_drive_file_id to Resource model

Revision ID: 428d1744bee5
Revises: 1f4ef68b0f71
Create Date: 2026-01-16 12:40:04.400679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '428d1744bee5'
down_revision = '1f4ef68b0f71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preview_drive_file_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.drop_column('preview_drive_file_id')

    # ### end Alembic commands ###
