"""Add tags to Resource

Revision ID: 6823a91ab46a
Revises: 03a1b3c908b2
Create Date: 2026-01-31 16:54:03.626948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6823a91ab46a'
down_revision = '03a1b3c908b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('home_content', schema=None) as batch_op:
        batch_op.drop_column('contacts_section_title')
        batch_op.drop_column('contacts_section_description')

    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.drop_column('tags')

    with op.batch_alter_table('home_content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contacts_section_description', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('contacts_section_title', sa.VARCHAR(length=200), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
