"""Add features_title and features_subtitle to HomeContent

Revision ID: 6ab6bc1187dc
Revises: f3501aeafcb7
Create Date: 2026-01-22 19:55:57.895199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ab6bc1187dc'
down_revision = 'f3501aeafcb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('home_content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('features_title', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('features_subtitle', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('home_content', schema=None) as batch_op:
        batch_op.drop_column('features_subtitle')
        batch_op.drop_column('features_title')

    # ### end Alembic commands ###
