"""Add passed and folder lock fields

Revision ID: 79d1b1ac1076
Revises: 6ab6bc1187dc
Create Date: 2026-01-23 14:31:07.089627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79d1b1ac1076'
down_revision = '6ab6bc1187dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_assignment_submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passed', sa.Boolean(), nullable=True))

    with op.batch_alter_table('course_content_folder', schema=None) as batch_op:
        batch_op.add_column(sa.Column('locked_until_assignment_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'course_assignment', ['locked_until_assignment_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_content_folder', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('locked_until_assignment_id')

    with op.batch_alter_table('course_assignment_submission', schema=None) as batch_op:
        batch_op.drop_column('passed')

    # ### end Alembic commands ###
