"""Make about_subtitle TEXT

Revision ID: 88e571a01ac0
Revises: 79d1b1ac1076
Create Date: 2026-01-28 10:30:39.277623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88e571a01ac0'
down_revision = '79d1b1ac1076'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('home_content', schema=None) as batch_op:
        batch_op.alter_column('about_subtitle',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('home_content', schema=None) as batch_op:
        batch_op.alter_column('about_subtitle',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###
