"""Add is_image_file field to Resource model

Revision ID: 95c61dd4b257
Revises: 428d1744bee5
Create Date: 2026-01-16 14:27:10.296886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95c61dd4b257'
down_revision = '428d1744bee5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_image_file', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.drop_column('is_image_file')

    # ### end Alembic commands ###
