"""Make access_pin and pin_expires_at nullable for optional PIN protection

Revision ID: 975d518e8069
Revises: 6823a91ab46a
Create Date: 2026-01-31 17:16:58.348079

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '975d518e8069'
down_revision = '6823a91ab46a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.alter_column('access_pin',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('pin_expires_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.alter_column('pin_expires_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('access_pin',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)

    # ### end Alembic commands ###
