"""Add Google Drive fields to Resource and CourseContent models

Revision ID: add_drive_fields
Revises: 80aea2ea5f83
Create Date: 2026-01-03 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_drive_fields'
down_revision = '80aea2ea5f83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_assignment_submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('drive_file_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('drive_view_link', sa.String(length=300), nullable=True))
        batch_op.drop_column('file_path')

    with op.batch_alter_table('course_content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('drive_file_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('drive_view_link', sa.String(length=300), nullable=True))

    with op.batch_alter_table('pdf_document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('drive_file_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('drive_view_link', sa.String(length=300), nullable=True))
        batch_op.drop_column('file_path')

    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.add_column(sa.Column('drive_file_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('drive_view_link', sa.String(length=300), nullable=True))
        batch_op.drop_column('file_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_url', sa.String(length=300), nullable=True))
        batch_op.drop_column('drive_view_link')
        batch_op.drop_column('drive_file_id')

    with op.batch_alter_table('pdf_document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.String(length=500), nullable=True))
        batch_op.drop_column('drive_view_link')
        batch_op.drop_column('drive_file_id')

    with op.batch_alter_table('course_content', schema=None) as batch_op:
        batch_op.drop_column('drive_view_link')
        batch_op.drop_column('drive_file_id')

    with op.batch_alter_table('course_assignment_submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.String(length=300), nullable=True))
        batch_op.drop_column('drive_view_link')
        batch_op.drop_column('drive_file_id')
    # ### end Alembic commands ###