"""Add course tab label fields for translation

Revision ID: b510be4dc5b3
Revises: 312c4937cc2e
Create Date: 2026-01-19 17:07:49.340829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b510be4dc5b3'
down_revision = '312c4937cc2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tab_content_label', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('tab_assignments_label', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('tab_announcements_label', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('tab_reviews_label', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('tab_reviews_label')
        batch_op.drop_column('tab_announcements_label')
        batch_op.drop_column('tab_assignments_label')
        batch_op.drop_column('tab_content_label')

    # ### end Alembic commands ###
