"""Add grade and comment to CourseAssignmentSubmission

Revision ID: e1130138e6e5
Revises: 
Create Date: 2026-01-10 15:35:00.516118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1130138e6e5'
down_revision = 'b5dc9eedb1ad'
branch_labels = None
depends_on = None


from sqlalchemy import inspect

def upgrade():
    # --- home_content ---
    with op.batch_alter_table('home_content') as batch_op:
        batch_op.alter_column(
            'about_subtitle',
            existing_type=sa.TEXT(),
            type_=sa.Text(),
            existing_nullable=True,
            existing_server_default=sa.text(
                "'Join our learning community and discover amazing features.'"
            )
        )
        batch_op.alter_column(
            'about_features',
            existing_type=sa.TEXT(),
            type_=sa.JSON(),
            existing_nullable=True,
            existing_server_default=sa.text("'[]'")
        )

    bind = op.get_bind()
    inspector = inspect(bind)

    # --- pdf_document ---
    pdf_cols = [c["name"] for c in inspector.get_columns("pdf_document")]
    with op.batch_alter_table('pdf_document') as batch_op:
        if 'drive_file_id' not in pdf_cols:
            batch_op.add_column(sa.Column('drive_file_id', sa.String(length=100), nullable=True))
        if 'drive_view_link' not in pdf_cols:
            batch_op.add_column(sa.Column('drive_view_link', sa.String(length=300), nullable=True))
        if 'file_path' in pdf_cols:
            batch_op.drop_column('file_path')

    # --- user ---
    user_cols = [c["name"] for c in inspector.get_columns("user")]
    with op.batch_alter_table('user') as batch_op:
        if 'google_access_token' not in user_cols:
            batch_op.add_column(sa.Column('google_access_token', sa.Text(), nullable=True))
        if 'google_refresh_token' not in user_cols:
            batch_op.add_column(sa.Column('google_refresh_token', sa.Text(), nullable=True))
        if 'google_token_expiry' not in user_cols:
            batch_op.add_column(sa.Column('google_token_expiry', sa.DateTime(), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('google_token_expiry')
        batch_op.drop_column('google_refresh_token')
        batch_op.drop_column('google_access_token')

    with op.batch_alter_table('pdf_document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.VARCHAR(length=500), nullable=False))
        batch_op.drop_column('drive_view_link')
        batch_op.drop_column('drive_file_id')

    with op.batch_alter_table('home_content', schema=None) as batch_op:
        batch_op.alter_column('about_features',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'"))
        batch_op.alter_column('about_subtitle',
               existing_type=sa.Text(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'Join our learning community and discover amazing features.'"))

    # ### end Alembic commands ###
