"""Add grade and comment to CourseAssignmentSubmission

Revision ID: e1130138e6e5
Revises: 
Create Date: 2026-01-10 15:35:00.516118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1130138e6e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('home_content', schema=None) as batch_op:
        batch_op.alter_column('about_subtitle',
               existing_type=sa.TEXT(),
               type_=sa.Text(),
               existing_nullable=True,
               existing_server_default=sa.text("'Join our learning community and discover amazing features.'"))
        batch_op.alter_column('about_features',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'"))

    with op.batch_alter_table('pdf_document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('drive_file_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('drive_view_link', sa.String(length=300), nullable=True))
        batch_op.drop_column('file_path')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_access_token', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('google_refresh_token', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('google_token_expiry', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('google_token_expiry')
        batch_op.drop_column('google_refresh_token')
        batch_op.drop_column('google_access_token')

    with op.batch_alter_table('pdf_document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.VARCHAR(length=500), nullable=False))
        batch_op.drop_column('drive_view_link')
        batch_op.drop_column('drive_file_id')

    with op.batch_alter_table('home_content', schema=None) as batch_op:
        batch_op.alter_column('about_features',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'"))
         batch_op.alter_column('about_subtitle',
             existing_type=sa.Text(),
             type_=sa.TEXT(),
             existing_nullable=True,
             existing_server_default=sa.text("'Join our learning community and discover amazing features.'"))

    # ### end Alembic commands ###
